#!/bin/bash

curl --header "Content-Type: application/json" \
	--request POST \
	--data '{
		"username": "Foobar",
		"password": "default",
		"password2": "default"
		}' \
	https://todo-app-api123.herokuapp.com/api/register
