#!/bin/bash

curl --header "Authorization: Bearer ${1}" \
	--header "Content-Type: application/json" \
	--request POST \
	--data '{
		"text": "kup ziemniaki"
	}' \
	http://localhost:5000/api/lists/1/tasks
