#!/bin/bash

curl --header "Authorization: Bearer ${1}" \
	--header "Content-Type: application/json" \
	--request PUT \
	--data '{
		"text": "kup ziemniaki",
		"active": true
	}' \
	http://localhost:5000/api/lists/1/tasks/1
